### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by michelesr** [valentinvieriu/visual-hacker-news#1]
Your project is beautiful and it's going to be my main HN frontend. It would be great  to add a way to view comments. Even a link to the article related comment page on `news.ycombinator.com` would be a nice feature.

**Comment by valentinvieriu** [comment]
It's already on the list of things to be implemented. Thank you for the feedback!
I'm thinking something like http://insin.github.io/react-hn/#/?_k=sb2snp

**Comment by michelesr** [comment]
That would be awesome! Thanks!

**Comment by michelesr** [comment]
In the meanwhile I implemented a simple href to ycombinator for my local fork:
![2016-01-26-231042_1366x768_scrot](https://cloud.githubusercontent.com/assets/2516077/12596927/d45c74cc-c482-11e5-85ef-5a577f64e673.png)

**Comment by valentinvieriu** [comment]
@michelesr I've implemented quickly something similar to your proposal
#662dc9a

**Comment by michelesr** [comment]
Great!
