### ISSUE TITLE
[Question] How Link preview image works

### ISSUE THREAD

**Issue by Kikobeats** [valentinvieriu/visual-hacker-news#3]
Hey,

Thanks for share your Vuew Hacker News fork, it's awesome! I like it because it has the feature of see the image link preview 😄.

I'm reading the code for see how you do that. The first thing I see was [fetchImages.js](https://github.com/valentinvieriu/visual-hacker-news/blob/master/fetchImages.js), but actually [looks like you are don't use it currently](https://github.com/valentinvieriu/visual-hacker-news/blob/master/server.js#L51). 

I suppose that the preview image is stored in the firebase database. It is correct?

**Comment by yunyu** [comment]
It looks like it forwards the request to a configurable external service and pipes it back: https://github.com/valentinvieriu/visual-hacker-news/blob/528fd47738e7fb65bd9caa155c9a00cab92a574a/server.js#L133

**Comment by valentinvieriu** [comment]
hi @Kikobeats,

Thank you for the interest.

For the preview generation I use a PhantomJS custom server. As PhantomJs is dying, I'm still waiting for the Chrome headless to be stable enough so I can switch. 

This is the reason that I've not shared the PhantomJS screenshot code yet.

**Comment by Kikobeats** [comment]
Interesting! Thanks for your comment.

Why not use something more lightweight than phantom? for example: https://github.com/sindresorhus/pageres

**Comment by valentinvieriu** [comment]
If you look under the hood you will see that uses Phantomjs too :)

**Comment by Kikobeats** [comment]
oh, that's true. Half internet is broken because phantom 😂

**Comment by valentinvieriu** [comment]
@yunyu you are right. I'm running an internal docker service that does the screenshots and then pipe the image to the `/thumbnail` endpoint so that Cloudflare caches this for me on the CDN side.
The screenshot code is not really ready for primetime :) it's more of a hack solution, but uses [phantom-pool](https://github.com/binded/phantom-pool) under the hood for faster phantom-js generation.

**Comment by Kikobeats** [comment]
Hey @valentinvieriu, take a look into this https://github.com/graphcool/chromeless 😄

**Comment by valentinvieriu** [comment]
@Kikobeats Thank you. I've just read that the other day too. Actually we already have a google chrome headless solution for [hnews](hnews.xyz).
The documentation it's not there, but I'm using [node-screenshots](https://github.com/valentinvieriu/node-screenshots) for the nodejs screenshot and a custom docker image for the  [Chrome Headless](https://github.com/valentinvieriu/chrome-headless);

Have a look over those 2 repos, you can run them on your own, by running docker-compose up

When I'll have more time I'll add some documentation, but I'm quite bad at this.
