### ISSUE TITLE
Preview images are missing

### ISSUE THREAD

**Issue by emanuelmutschlechner** [valentinvieriu/visual-hacker-news#4]
Is the screenshot functionality broken? I've noticed the missing images a few weeks ago.

![hnews xyz_top](https://user-images.githubusercontent.com/27734375/46819520-3bf3a300-cd84-11e8-90d2-c0243a0ecd66.png)

**Comment by BenjaminBini** [comment]
Same here.

**Comment by valentinvieriu** [comment]
My headless Chrome Docker image went down. From time to time it just hangs. Cannot figure out what's the issue, and just need to give it a restart from time to time. 
Sorry

**Comment by BenjaminBini** [comment]
Thanks. Just wanted to tell you how great this website is. It became my main way to browse HN nowadays.
